kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  VAULT_ADDR: "https://hcptest.devops.tech.ec.europa.eu"
  VAULT_TOKEN: "***"
  VAULT_NAMESPACE: "EC.DIGIT-B2.AMS"
  AVP_AUTH_TYPE: "token"
  AVP_TYPE: "vault"
