kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_TYPE: "awssecretsmanager"
  AWS_REGION: "eu-west-1"
  AWS_ACCESS_KEY_ID: "***"
  AWS_SECRET_ACCESS_KEY: "***"
